/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as GoogleReviewsRouteImport } from './routes/google-reviews'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as RecentWorkRouteImport } from './routes/recent-work'
import { Route as SignBoardsRouteImport } from './routes/sign-boards'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ThankYouRouteImport } from './routes/thank-you'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const GoogleReviewsRoute = GoogleReviewsRouteImport.update({
  id: '/google-reviews',
  path: '/google-reviews',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const RecentWorkRoute = RecentWorkRouteImport.update({
  id: '/recent-work',
  path: '/recent-work',
  getParentRoute: () => rootRouteImport,
} as any)
const SignBoardsRoute = SignBoardsRouteImport.update({
  id: '/sign-boards',
  path: '/sign-boards',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ThankYouRoute = ThankYouRouteImport.update({
  id: '/thank-you',
  path: '/thank-you',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/faq': typeof FaqRoute
  '/google-reviews': typeof GoogleReviewsRoute
  '/privacy': typeof PrivacyRoute
  '/recent-work': typeof RecentWorkRoute
  '/sign-boards': typeof SignBoardsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/thank-you': typeof ThankYouRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/faq': typeof FaqRoute
  '/google-reviews': typeof GoogleReviewsRoute
  '/privacy': typeof PrivacyRoute
  '/recent-work': typeof RecentWorkRoute
  '/sign-boards': typeof SignBoardsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/thank-you': typeof ThankYouRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/faq': typeof FaqRoute
  '/google-reviews': typeof GoogleReviewsRoute
  '/privacy': typeof PrivacyRoute
  '/recent-work': typeof RecentWorkRoute
  '/sign-boards': typeof SignBoardsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/thank-you': typeof ThankYouRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/faq'
    | '/google-reviews'
    | '/privacy'
    | '/recent-work'
    | '/sign-boards'
    | '/sitemap.xml'
    | '/thank-you'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/faq'
    | '/google-reviews'
    | '/privacy'
    | '/recent-work'
    | '/sign-boards'
    | '/sitemap.xml'
    | '/thank-you'
  id:
    | '__root__'
    | '/'
    | '/faq'
    | '/google-reviews'
    | '/privacy'
    | '/recent-work'
    | '/sign-boards'
    | '/sitemap.xml'
    | '/thank-you'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  FaqRoute: typeof FaqRoute
  GoogleReviewsRoute: typeof GoogleReviewsRoute
  PrivacyRoute: typeof PrivacyRoute
  RecentWorkRoute: typeof RecentWorkRoute
  SignBoardsRoute: typeof SignBoardsRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  ThankYouRoute: typeof ThankYouRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/google-reviews': {
      id: '/google-reviews'
      path: '/google-reviews'
      fullPath: '/google-reviews'
      preLoaderRoute: typeof GoogleReviewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recent-work': {
      id: '/recent-work'
      path: '/recent-work'
      fullPath: '/recent-work'
      preLoaderRoute: typeof RecentWorkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-boards': {
      id: '/sign-boards'
      path: '/sign-boards'
      fullPath: '/sign-boards'
      preLoaderRoute: typeof SignBoardsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/thank-you': {
      id: '/thank-you'
      path: '/thank-you'
      fullPath: '/thank-you'
      preLoaderRoute: typeof ThankYouRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  FaqRoute: FaqRoute,
  GoogleReviewsRoute: GoogleReviewsRoute,
  PrivacyRoute: PrivacyRoute,
  RecentWorkRoute: RecentWorkRoute,
  SignBoardsRoute: SignBoardsRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  ThankYouRoute: ThankYouRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
